// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3BAFCybRthMSjToNHeiFSjowKf2Mgog',
    appId: '1:633626064514:web:4eb5f3153dcfb38930a69b',
    messagingSenderId: '633626064514',
    projectId: 'fir-a-3377a',
    authDomain: 'fir-a-3377a.firebaseapp.com',
    storageBucket: 'fir-a-3377a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxg9D7qa7jfVsMJEeRO-6ES1RPfoghvIA',
    appId: '1:633626064514:android:dd8182d72171a8f530a69b',
    messagingSenderId: '633626064514',
    projectId: 'fir-a-3377a',
    storageBucket: 'fir-a-3377a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaPhXgRbGO7HP0iJmrsRklzPeHF_ZyyQ',
    appId: '1:633626064514:ios:6c74bdc1bd92dac930a69b',
    messagingSenderId: '633626064514',
    projectId: 'fir-a-3377a',
    storageBucket: 'fir-a-3377a.firebasestorage.app',
    iosBundleId: 'com.example.twoListviewInColumn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgaPhXgRbGO7HP0iJmrsRklzPeHF_ZyyQ',
    appId: '1:633626064514:ios:6c74bdc1bd92dac930a69b',
    messagingSenderId: '633626064514',
    projectId: 'fir-a-3377a',
    storageBucket: 'fir-a-3377a.firebasestorage.app',
    iosBundleId: 'com.example.twoListviewInColumn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx3BAFCybRthMSjToNHeiFSjowKf2Mgog',
    appId: '1:633626064514:web:5edb3e538f605db930a69b',
    messagingSenderId: '633626064514',
    projectId: 'fir-a-3377a',
    authDomain: 'fir-a-3377a.firebaseapp.com',
    storageBucket: 'fir-a-3377a.firebasestorage.app',
  );
}
